#!/usr/bin/env bash

# Post-clone network setup script for Ubuntu VMs cloned from a template.
# Run this after importing a VM clone to configure static networking and regenerate IDs.

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: post_clone_network.sh --ip <ADDRESS> --gateway <GATEWAY> --netmask <NETMASK>|--prefix <PREFIX> [--dns <DNS1,DNS2,...>] [--interface <IFACE>] [--hostname <HOST>]

Arguments:
  --ip          IPv4 address to assign (e.g. 192.168.10.20)
  --gateway     Default gateway (e.g. 192.168.10.1)
  --netmask     Subnet mask (e.g. 255.255.255.0)
  --prefix      CIDR prefix length (e.g. 24). Use instead of --netmask.
  --dns         Comma-separated DNS servers (default: 1.1.1.1,8.8.8.8)
  --interface   Network interface name (default: first non-loopback interface)
  --hostname    Optional hostname to set for this VM

Examples:
  post_clone_network.sh --ip 10.0.0.50 --gateway 10.0.0.1 --prefix 24 --dns 1.1.1.1,8.8.4.4
  post_clone_network.sh --ip 192.168.5.12 --gateway 192.168.5.1 --netmask 255.255.255.0 --interface ens160 --hostname web-01
EOF
}

if [[ ${EUID} -ne 0 ]]; then
  echo "This script must be run as root." >&2
  exit 1
fi

IP_ADDRESS=""
GATEWAY=""
NETMASK=""
PREFIX=""
DNS_SERVERS="1.1.1.1,8.8.8.8"
INTERFACE=""
HOSTNAME=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ip)
      IP_ADDRESS="$2"
      shift 2
      ;;
    --gateway)
      GATEWAY="$2"
      shift 2
      ;;
    --netmask)
      NETMASK="$2"
      shift 2
      ;;
    --prefix)
      PREFIX="$2"
      shift 2
      ;;
    --dns)
      DNS_SERVERS="$2"
      shift 2
      ;;
    --interface)
      INTERFACE="$2"
      shift 2
      ;;
    --hostname)
      HOSTNAME="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z ${IP_ADDRESS} || -z ${GATEWAY} ]]; then
  echo "Error: --ip and --gateway are required." >&2
  usage
  exit 1
fi

if [[ -z ${PREFIX} && -z ${NETMASK} ]]; then
  echo "Error: provide either --prefix or --netmask." >&2
  usage
  exit 1
fi

if [[ -n ${PREFIX} && -n ${NETMASK} ]]; then
  echo "Error: use only one of --prefix or --netmask." >&2
  usage
  exit 1
fi

if [[ -z ${INTERFACE} ]]; then
  INTERFACE="$(ip -o link show | awk -F': ' '$2 != "lo" {print $2; exit}')"
  if [[ -z ${INTERFACE} ]]; then
    echo "Unable to detect a non-loopback interface. Specify --interface explicitly." >&2
    exit 1
  fi
fi

convert_netmask_to_prefix() {
  local mask=$1
  IFS='.' read -r o1 o2 o3 o4 <<<"${mask}"
  local binary=""
  for octet in "${o1}" "${o2}" "${o3}" "${o4}"; do
    local bin_octet
    bin_octet=$(bc <<<"obase=2;${octet}")
    binary+=$(printf '%08s' "${bin_octet}" | tr ' ' '0')
  done
  printf '%s\n' "${binary}" | tr -cd '1' | wc -c | awk '{print $1}'
}

if [[ -z ${PREFIX} ]]; then
  if ! command -v bc >/dev/null 2>&1; then
    echo "bc is required to convert netmask to prefix. Install bc or supply --prefix." >&2
    exit 1
  fi
  PREFIX=$(convert_netmask_to_prefix "${NETMASK}")
fi

dns_yaml=$(printf '%s' "${DNS_SERVERS}" | tr ',' '\n' | awk 'NF {printf "          - %s\n", $0}')

NETPLAN_FILE="/etc/netplan/99-post-clone.yaml"

cat > "${NETPLAN_FILE}" <<EOF
# Generated by post_clone_network.sh
network:
  version: 2
  renderer: networkd
  ethernets:
    ${INTERFACE}:
      addresses:
        - ${IP_ADDRESS}/${PREFIX}
      routes:
        - to: default
          via: ${GATEWAY}
      nameservers:
        addresses:
$(printf '%s' "${dns_yaml}")
EOF

echo "Applying netplan configuration from ${NETPLAN_FILE}..."
netplan apply

if [[ -n ${HOSTNAME} ]]; then
  echo "Setting hostname to ${HOSTNAME}..."
  hostnamectl set-hostname "${HOSTNAME}"
fi

if [[ ! -s /etc/machine-id ]]; then
  echo "Generating new machine-id..."
  systemd-machine-id-setup
fi

echo "Regenerating SSH host keys..."
ssh-keygen -A

echo "Network configuration complete. Current addresses:"
ip -o -4 addr show "${INTERFACE}"

